#!/usr/bin/env python3
"""Generate a KiCad legacy netlist from components.csv + nets.csv.

The legacy netlist format is plain text and importable directly into
KiCad's PCB editor (Pcbnew → Import → Specctra Netlist or via the
File → Import Netlist menu in modern KiCad). It carries components +
connectivity, which is everything the PCB editor needs to start
placing footprints.

Output is deterministic: same input bytes → same output bytes.
test_oi_8hp_tcu_schematic asserts this.

Run from this directory:
    python3 gen_netlist.py

Reference: legacy KiCad netlist format
https://docs.kicad.org/legacy_help/en/help/_chapter_3.html#netlist-format
"""
from __future__ import annotations

import csv
import sys
from collections import OrderedDict, defaultdict
from pathlib import Path


HERE = Path(__file__).resolve().parent


def load_csv(path: Path) -> list[dict]:
    with open(path, newline="") as fh:
        rdr = csv.DictReader(filter(lambda r: not r.startswith("#"), fh))
        return [r for r in rdr if r.get("ref") or r.get("net")]


def main() -> int:
    components = load_csv(HERE / "components.csv")
    nets_rows = load_csv(HERE / "nets.csv")

    # Validate: every component-pin pair in nets.csv references a known component.
    comp_refs = {c["ref"] for c in components}
    bad = []
    for r in nets_rows:
        if r["component"] != "—" and r["component"] not in comp_refs:
            bad.append(r)
    if bad:
        print("nets.csv references unknown components:", file=sys.stderr)
        for b in bad:
            print(f"  {b['net']}: {b['component']} pin {b['pin']}", file=sys.stderr)
        return 2

    # Group rows by net, preserving net insertion order from nets.csv.
    nets: OrderedDict[str, list[tuple[str, str, str]]] = OrderedDict()
    for r in nets_rows:
        nets.setdefault(r["net"], []).append(
            (r["component"], r["pin"], r["note"])
        )

    # Build the legacy-netlist output.
    out: list[str] = []
    out.append("(export (version D)")
    out.append("  (design")
    out.append('    (source "proposals/hardware/oi_8hp_tcu/nets.csv")')
    out.append('    (date "regenerated by gen_netlist.py")')
    out.append('    (tool "8hp-tcu-contrib gen_netlist.py")')
    out.append("  )")

    # Components
    out.append("  (components")
    for c in components:
        out.append(f'    (comp (ref "{c["ref"]}")')
        out.append(f'      (value "{c["value"]}")')
        if c.get("part_number") and c["part_number"] not in ("", "—"):
            out.append(f'      (part_number "{c["part_number"]}")')
        if c.get("kicad_lib") and c["kicad_lib"] not in ("", "—"):
            out.append(f'      (libsource (lib "{c["kicad_lib"].split(":")[0]}")'
                        f' (part "{c["kicad_lib"].split(":")[-1]}"))')
        if c.get("package") and c["package"] not in ("", "—"):
            out.append(f'      (footprint "{c["package"]}")')
        out.append("    )")
    out.append("  )")

    # Nets — assign numeric net codes in insertion order.
    out.append("  (nets")
    for code, (net_name, nodes) in enumerate(nets.items(), start=1):
        out.append(f'    (net (code {code}) (name "{net_name}")')
        for ref, pin, note in nodes:
            if ref == "—":  # synthetic / commentary row
                continue
            out.append(f'      (node (ref "{ref}") (pin "{pin}"))')
        out.append("    )")
    out.append("  )")

    out.append(")")

    netlist_text = "\n".join(out) + "\n"
    (HERE / "oi_8hp_tcu.net").write_text(netlist_text)

    n_components = len(components)
    n_nets = len(nets)
    n_nodes = sum(
        1 for r in nets_rows
        if r["component"] not in ("—", "")
    )
    print(f"wrote {HERE / 'oi_8hp_tcu.net'}")
    print(f"  {n_components} components, {n_nets} nets, {n_nodes} nodes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
