/**
 * @file zf8hp_tcu.h
 *
 * @brief This header file was generated by cantools version 41.3.1 Sun May 10 15:12:36 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef ZF8HP_TCU_H
#define ZF8HP_TCU_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_FRAME_ID (0x520u)
#define ZF8HP_TCU_VCU_VEHICLE_INFO_FRAME_ID (0x521u)
#define ZF8HP_TCU_TCU_STATUS1_FRAME_ID (0x540u)
#define ZF8HP_TCU_TCU_STATUS2_FRAME_ID (0x541u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_FRAME_ID (0x542u)

/* Frame lengths in bytes. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_LENGTH (8u)
#define ZF8HP_TCU_VCU_VEHICLE_INFO_LENGTH (8u)
#define ZF8HP_TCU_TCU_STATUS1_LENGTH (8u)
#define ZF8HP_TCU_TCU_STATUS2_LENGTH (8u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_LENGTH (8u)

/* Extended or standard frame types. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_IS_EXTENDED (0)
#define ZF8HP_TCU_VCU_VEHICLE_INFO_IS_EXTENDED (0)
#define ZF8HP_TCU_TCU_STATUS1_IS_EXTENDED (0)
#define ZF8HP_TCU_TCU_STATUS2_IS_EXTENDED (0)
#define ZF8HP_TCU_TCU_PUMP_STATUS_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_P_CHOICE (0u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_R_CHOICE (1u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_N_CHOICE (2u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_D_CHOICE (3u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_S_CHOICE (4u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M1_CHOICE (5u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M2_CHOICE (6u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M3_CHOICE (7u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M4_CHOICE (8u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M5_CHOICE (9u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M6_CHOICE (10u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M7_CHOICE (11u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_M8_CHOICE (12u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_LIMP_CHOICE (13u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_INVALID_CHOICE (15u)

#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_COMFORT_CHOICE (0u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_SPORT_CHOICE (1u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_ECO_CHOICE (2u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_SNOW_CHOICE (3u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_MANUAL_CHOICE (4u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_LAUNCH_CHOICE (5u)
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_RESERVED_CHOICE (15u)

#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_NEUTRAL_CHOICE (0u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G1_CHOICE (1u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G2_CHOICE (2u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G3_CHOICE (3u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G4_CHOICE (4u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G5_CHOICE (5u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G6_CHOICE (6u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G7_CHOICE (7u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_G8_CHOICE (8u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_REVERSE_CHOICE (9u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_SHIFTING_CHOICE (14u)
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_INVALID_CHOICE (15u)

#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_P_CHOICE (0u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_R_CHOICE (1u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_N_CHOICE (2u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_D_CHOICE (3u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_S_CHOICE (4u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M1_CHOICE (5u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M2_CHOICE (6u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M3_CHOICE (7u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M4_CHOICE (8u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M5_CHOICE (9u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M6_CHOICE (10u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M7_CHOICE (11u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_M8_CHOICE (12u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_LIMP_CHOICE (13u)
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_INVALID_CHOICE (15u)

#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_INIT_CHOICE (0u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_IDLE_CHOICE (1u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_PARK_CHOICE (2u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_REVERSE_CHOICE (3u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_NEUTRAL_CHOICE (4u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_DRIVE_CHOICE (5u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_SHIFTING_CHOICE (6u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_NEUTRAL_HOLD_CHOICE (7u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_LIMP_CHOICE (8u)
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_FAULT_CHOICE (15u)

#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_OFF_CHOICE (0u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_COLDSTART_CHOICE (1u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_PHASE2_READY_CHOICE (2u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_RUN_CHOICE (3u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_WATCHDOG_FAULT_CHOICE (4u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_ALT_FAULT_CHOICE (5u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_NOT_PRESENT_CHOICE (6u)
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_RESERVED_CHOICE (7u)

/* Frame Names. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_NAME "VCU_GearRequest"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_NAME "VCU_VehicleInfo"
#define ZF8HP_TCU_TCU_STATUS1_NAME "TCU_Status1"
#define ZF8HP_TCU_TCU_STATUS2_NAME "TCU_Status2"
#define ZF8HP_TCU_TCU_PUMP_STATUS_NAME "TCU_PumpStatus"

/* Signal Names. */
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TARGET_GEAR_NAME "TargetGear"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_DRIVE_MODE_NAME "DriveMode"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_ACCEL_PEDAL_NAME "AccelPedal"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_TORQUE_REQUEST_NAME "TorqueRequest"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_VEHICLE_SPEED_NAME "VehicleSpeed"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_BRAKE_PRESSED_NAME "BrakePressed"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_FAULT_CLEAR_NAME "FaultClear"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_FORCE_SHIFT_NAME "ForceShift"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_VCU_READY_NAME "VcuReady"
#define ZF8HP_TCU_VCU_GEAR_REQUEST_COUNTER520_NAME "Counter520"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_ACTUAL_TORQUE_NAME "ActualTorque"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_MOTOR_RPM_NAME "MotorRPM"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_MOTOR_TEMP_NAME "MotorTemp"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_BATTERY_SOC_NAME "BatterySOC"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_CHARGING_ACTIVE_NAME "ChargingActive"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_REGEN_ALLOWED_NAME "RegenAllowed"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_HV_PRESENT_NAME "HVPresent"
#define ZF8HP_TCU_VCU_VEHICLE_INFO_COUNTER521_NAME "Counter521"
#define ZF8HP_TCU_TCU_STATUS1_CURRENT_GEAR_NAME "CurrentGear"
#define ZF8HP_TCU_TCU_STATUS1_TARGET_GEAR_ECHO_NAME "TargetGearEcho"
#define ZF8HP_TCU_TCU_STATUS1_TCU_STATE_NAME "TcuState"
#define ZF8HP_TCU_TCU_STATUS1_SHIFT_IN_PROGRESS_NAME "ShiftInProgress"
#define ZF8HP_TCU_TCU_STATUS1_TCU_READY_NAME "TcuReady"
#define ZF8HP_TCU_TCU_STATUS1_ANY_FAULT_NAME "AnyFault"
#define ZF8HP_TCU_TCU_STATUS1_PARK_LOCK_NAME "ParkLock"
#define ZF8HP_TCU_TCU_STATUS1_INPUT_SHAFT_RPM_NAME "InputShaftRPM"
#define ZF8HP_TCU_TCU_STATUS1_OUTPUT_SHAFT_RPM_NAME "OutputShaftRPM"
#define ZF8HP_TCU_TCU_STATUS1_OIL_TEMP_NAME "OilTemp"
#define ZF8HP_TCU_TCU_STATUS1_LINE_PRESSURE_NAME "LinePressure"
#define ZF8HP_TCU_TCU_STATUS2_SOL_A_CURRENT_NAME "SolACurrent"
#define ZF8HP_TCU_TCU_STATUS2_SOL_B_CURRENT_NAME "SolBCurrent"
#define ZF8HP_TCU_TCU_STATUS2_FAULT_BITS_NAME "FaultBits"
#define ZF8HP_TCU_TCU_STATUS2_SHIFT_COUNT_NAME "ShiftCount"
#define ZF8HP_TCU_TCU_STATUS2_TCU_HW_TEMP_NAME "TcuHwTemp"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_STATE_NAME "PumpState"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_RUN_ACK_NAME "PumpRunAck"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_LIN_FAULT_NAME "PumpLinFault"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_ALT_FAULT_NAME "PumpAltFault"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_RPM_NAME "PumpRPM"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_VOLTAGE_NAME "PumpVoltage"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_CURRENT_RAW_NAME "PumpCurrentRaw"
#define ZF8HP_TCU_TCU_PUMP_STATUS_PUMP_RETRY_COUNT_NAME "PumpRetryCount"
#define ZF8HP_TCU_TCU_PUMP_STATUS_COUNTER542_NAME "Counter542"

/**
 * Signals in message VCU_GearRequest.
 *
 * VCU -> TCU command frame, 20 ms cyclic
 *
 * All signal values are as on the CAN bus.
 */
struct zf8hp_tcu_vcu_gear_request_t {
    /**
     * Requested gear position. Manual M1..M8 = hold that gear, S = sport auto, Limp = TCU choose safe gear
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t target_gear;

    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t drive_mode;

    /**
     * Range: 0..200 (0..100 %)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t accel_pedal;

    /**
     * Driver-requested torque at the wheels (signed). TCU may delay/reduce shifts based on this
     *
     * Range: -32768..32767 (-32768..32767 Nm)
     * Scale: 1
     * Offset: 0
     */
    int16_t torque_request;

    /**
     * Range: 0..65535 (0..655.35 km/h)
     * Scale: 0.01
     * Offset: 0
     */
    uint16_t vehicle_speed;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t brake_pressed;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t fault_clear;

    /**
     * If 1, request immediate shift to TargetGear ignoring smoothness logic (diagnostics)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t force_shift;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t vcu_ready;

    /**
     * Rolling 0..15 counter; TCU treats stale frames as VCU offline
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t counter520;
};

/**
 * Signals in message VCU_VehicleInfo.
 *
 * VCU -> TCU vehicle/torque context, 100 ms cyclic
 *
 * All signal values are as on the CAN bus.
 */
struct zf8hp_tcu_vcu_vehicle_info_t {
    /**
     * Range: -32768..32767 (-32768..32767 Nm)
     * Scale: 1
     * Offset: 0
     */
    int16_t actual_torque;

    /**
     * Range: -32768..32767 (-32768..32767 rpm)
     * Scale: 1
     * Offset: 0
     */
    int16_t motor_rpm;

    /**
     * Range: 0..255 (-40..215 C)
     * Scale: 1
     * Offset: -40
     */
    int8_t motor_temp;

    /**
     * Range: 0..200 (0..100 %)
     * Scale: 0.5
     * Offset: 0
     */
    uint8_t battery_soc;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t charging_active;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t regen_allowed;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t hv_present;

    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t counter521;
};

/**
 * Signals in message TCU_Status1.
 *
 * TCU -> VCU primary status, 20 ms cyclic
 *
 * All signal values are as on the CAN bus.
 */
struct zf8hp_tcu_tcu_status1_t {
    /**
     * 0=Neutral, 1..8=engaged forward gear, 9=Reverse, 14=mid-shift, 15=invalid
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t current_gear;

    /**
     * TCU's interpretation of last received TargetGear (handshake)
     *
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t target_gear_echo;

    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tcu_state;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t shift_in_progress;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t tcu_ready;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t any_fault;

    /**
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t park_lock;

    /**
     * Range: 0..65535 (0..65535 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t input_shaft_rpm;

    /**
     * Range: 0..65535 (0..65535 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t output_shaft_rpm;

    /**
     * Range: 0..255 (-40..215 C)
     * Scale: 1
     * Offset: -40
     */
    int8_t oil_temp;

    /**
     * Main hydraulic line pressure, 0.1 bar resolution
     *
     * Range: 0..255 (0..25.5 bar)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t line_pressure;
};

/**
 * Signals in message TCU_Status2.
 *
 * TCU -> VCU diagnostics, 100 ms cyclic
 *
 * All signal values are as on the CAN bus.
 */
struct zf8hp_tcu_tcu_status2_t {
    /**
     * Range: 0..65535 (0..65535 mA)
     * Scale: 1
     * Offset: 0
     */
    uint16_t sol_a_current;

    /**
     * Range: 0..65535 (0..65535 mA)
     * Scale: 1
     * Offset: 0
     */
    uint16_t sol_b_current;

    /**
     * Bit0=SolOpen Bit1=SolShort Bit2=OilHot Bit3=PressLow Bit4=SpeedSensor Bit5=LinComm Bit6=CanStale Bit7=OverTemp Bit8..15=reserved
     *
     * Range: 0..65535 (0..65535 -)
     * Scale: 1
     * Offset: 0
     */
    uint16_t fault_bits;

    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t shift_count;

    /**
     * Range: 0..255 (-40..215 C)
     * Scale: 1
     * Offset: -40
     */
    int8_t tcu_hw_temp;
};

/**
 * Signals in message TCU_PumpStatus.
 *
 * TCU -> VCU aux pump status (HZ hybrid 'box only), 100 ms cyclic
 *
 * All signal values are as on the CAN bus.
 */
struct zf8hp_tcu_tcu_pump_status_t {
    /**
     * TCU LIN state machine: Off / Coldstart (TX AA..0A..) / Phase2Ready (TX AA..42..) / Run (TX 55..42..) / WatchdogFault (0x32 byte0=0x40) / AltFault (0x32 byte0=0x50) / NotPresent (no LIN response after retries; non-hybrid 'box)
     *
     * Range: 0..7 (0..7 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_state;

    /**
     * Mirrors 0x32 byte 2 == 0x55 â€” pump confirms it's in run mode
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_run_ack;

    /**
     * Set when 0x32 byte 0 == 0x40 (LIN watchdog / comm fault)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_lin_fault;

    /**
     * Set when 0x32 byte 0 == 0x50 (alternate fault, less common)
     *
     * Range: 0..1 (0..1 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_alt_fault;

    /**
     * Pump speed in rpm. TCU computes from 0x32 byte 3 * 32
     *
     * Range: 0..65535 (0..65535 rpm)
     * Scale: 1
     * Offset: 0
     */
    uint16_t pump_rpm;

    /**
     * Pump supply voltage. From 0x32 byte 4 * 0.1 V
     *
     * Range: 0..255 (0..25.5 V)
     * Scale: 0.1
     * Offset: 0
     */
    uint8_t pump_voltage;

    /**
     * Raw 0x32 byte 5. Tracks motion but exact scaling not yet known (forum thread #7103, post 7)
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_current_raw;

    /**
     * Number of fault->coldstart cycles since last successful Run. Saturates at 255
     *
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t pump_retry_count;

    /**
     * Range: 0..15 (0..15 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t counter542;
};

/**
 * Pack message VCU_GearRequest.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int zf8hp_tcu_vcu_gear_request_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_vcu_gear_request_t *src_p,
    size_t size);

/**
 * Unpack message VCU_GearRequest.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int zf8hp_tcu_vcu_gear_request_unpack(
    struct zf8hp_tcu_vcu_gear_request_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VCU_GearRequest.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int zf8hp_tcu_vcu_gear_request_init(struct zf8hp_tcu_vcu_gear_request_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_target_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_target_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_target_gear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_target_gear_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_drive_mode_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_drive_mode_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_drive_mode_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_drive_mode_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_accel_pedal_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_accel_pedal_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_accel_pedal_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_accel_pedal_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t zf8hp_tcu_vcu_gear_request_torque_request_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_torque_request_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_torque_request_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_torque_request_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_vcu_gear_request_vehicle_speed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_vehicle_speed_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_vehicle_speed_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_vehicle_speed_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_brake_pressed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_brake_pressed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_brake_pressed_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_brake_pressed_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_fault_clear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_fault_clear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_fault_clear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_fault_clear_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_force_shift_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_force_shift_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_force_shift_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_force_shift_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_vcu_ready_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_vcu_ready_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_vcu_ready_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_vcu_ready_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_gear_request_counter520_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_gear_request_counter520_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_counter520_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_gear_request_counter520_is_in_phys_range(double value);

/**
 * Pack message VCU_VehicleInfo.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int zf8hp_tcu_vcu_vehicle_info_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_vcu_vehicle_info_t *src_p,
    size_t size);

/**
 * Unpack message VCU_VehicleInfo.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int zf8hp_tcu_vcu_vehicle_info_unpack(
    struct zf8hp_tcu_vcu_vehicle_info_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from VCU_VehicleInfo.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int zf8hp_tcu_vcu_vehicle_info_init(struct zf8hp_tcu_vcu_vehicle_info_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t zf8hp_tcu_vcu_vehicle_info_actual_torque_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_actual_torque_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_actual_torque_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_actual_torque_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int16_t zf8hp_tcu_vcu_vehicle_info_motor_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_motor_rpm_decode(int16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_motor_rpm_is_in_range(int16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_motor_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t zf8hp_tcu_vcu_vehicle_info_motor_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_motor_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_motor_temp_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_motor_temp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_vehicle_info_battery_soc_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_battery_soc_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_battery_soc_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_battery_soc_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_vehicle_info_charging_active_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_charging_active_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_charging_active_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_charging_active_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_vehicle_info_regen_allowed_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_regen_allowed_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_regen_allowed_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_regen_allowed_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_vehicle_info_hv_present_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_hv_present_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_hv_present_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_hv_present_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_vcu_vehicle_info_counter521_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_vcu_vehicle_info_counter521_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_counter521_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_vcu_vehicle_info_counter521_is_in_phys_range(double value);

/**
 * Pack message TCU_Status1.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int zf8hp_tcu_tcu_status1_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_status1_t *src_p,
    size_t size);

/**
 * Unpack message TCU_Status1.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int zf8hp_tcu_tcu_status1_unpack(
    struct zf8hp_tcu_tcu_status1_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from TCU_Status1.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int zf8hp_tcu_tcu_status1_init(struct zf8hp_tcu_tcu_status1_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_current_gear_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_current_gear_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_current_gear_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_current_gear_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_target_gear_echo_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_target_gear_echo_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_target_gear_echo_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_target_gear_echo_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_tcu_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_tcu_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_tcu_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_tcu_state_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_shift_in_progress_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_shift_in_progress_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_shift_in_progress_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_shift_in_progress_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_tcu_ready_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_tcu_ready_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_tcu_ready_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_tcu_ready_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_any_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_any_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_any_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_any_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_park_lock_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_park_lock_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_park_lock_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_park_lock_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_status1_input_shaft_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_input_shaft_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_input_shaft_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_input_shaft_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_status1_output_shaft_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_output_shaft_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_output_shaft_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_output_shaft_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t zf8hp_tcu_tcu_status1_oil_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_oil_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_oil_temp_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_oil_temp_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status1_line_pressure_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status1_line_pressure_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_line_pressure_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status1_line_pressure_is_in_phys_range(double value);

/**
 * Pack message TCU_Status2.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int zf8hp_tcu_tcu_status2_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_status2_t *src_p,
    size_t size);

/**
 * Unpack message TCU_Status2.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int zf8hp_tcu_tcu_status2_unpack(
    struct zf8hp_tcu_tcu_status2_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from TCU_Status2.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int zf8hp_tcu_tcu_status2_init(struct zf8hp_tcu_tcu_status2_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_status2_sol_a_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status2_sol_a_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_sol_a_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_sol_a_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_status2_sol_b_current_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status2_sol_b_current_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_sol_b_current_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_sol_b_current_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_status2_fault_bits_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status2_fault_bits_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_fault_bits_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_fault_bits_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_status2_shift_count_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status2_shift_count_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_shift_count_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_shift_count_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
int8_t zf8hp_tcu_tcu_status2_tcu_hw_temp_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_status2_tcu_hw_temp_decode(int8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_tcu_hw_temp_is_in_range(int8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_status2_tcu_hw_temp_is_in_phys_range(double value);

/**
 * Pack message TCU_PumpStatus.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int zf8hp_tcu_tcu_pump_status_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_pump_status_t *src_p,
    size_t size);

/**
 * Unpack message TCU_PumpStatus.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int zf8hp_tcu_tcu_pump_status_unpack(
    struct zf8hp_tcu_tcu_pump_status_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from TCU_PumpStatus.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int zf8hp_tcu_tcu_pump_status_init(struct zf8hp_tcu_tcu_pump_status_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_state_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_state_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_state_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_run_ack_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_run_ack_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_run_ack_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_run_ack_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_lin_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_lin_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_lin_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_lin_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_alt_fault_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_alt_fault_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_alt_fault_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_alt_fault_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t zf8hp_tcu_tcu_pump_status_pump_rpm_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_rpm_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_rpm_is_in_range(uint16_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_rpm_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_voltage_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_voltage_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_voltage_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_voltage_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_current_raw_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_current_raw_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_current_raw_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_current_raw_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_pump_retry_count_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_pump_retry_count_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_retry_count_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_pump_retry_count_is_in_phys_range(double value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t zf8hp_tcu_tcu_pump_status_counter542_encode(double value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
double zf8hp_tcu_tcu_pump_status_counter542_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_counter542_is_in_range(uint8_t value);

/**
 * Check that given physical value is in allowed range before encoding.
 *
 * Use this BEFORE calling _encode() to avoid silent integer overflow:
 *   encode(-1.0) on a [0,100] signal wraps to 255 and passes is_in_range().
 *   is_in_phys_range(-1.0) correctly returns false.
 *
 * @param[in] value Physical signal value to check.
 *
 * @return true if in range, false otherwise.
 */
bool zf8hp_tcu_tcu_pump_status_counter542_is_in_phys_range(double value);


#ifdef __cplusplus
}
#endif

#endif
