/**
 * @file zf8hp_tcu.c
 *
 * @brief This source file was generated by cantools version 41.3.1 Sun May 10 17:20:51 2026.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "zf8hp_tcu.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int zf8hp_tcu_vcu_gear_request_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_vcu_gear_request_t *src_p,
    size_t size)
{
    uint16_t torque_request;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->target_gear, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->drive_mode, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->accel_pedal, 0u, 0xffu);
    torque_request = (uint16_t)src_p->torque_request;
    dst_p[2] |= pack_left_shift_u16(torque_request, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(torque_request, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->vehicle_speed, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->vehicle_speed, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->brake_pressed, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->fault_clear, 1u, 0x02u);
    dst_p[6] |= pack_left_shift_u8(src_p->force_shift, 2u, 0x04u);
    dst_p[6] |= pack_left_shift_u8(src_p->vcu_ready, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->counter520, 0u, 0x0fu);

    return (8);
}

int zf8hp_tcu_vcu_gear_request_unpack(
    struct zf8hp_tcu_vcu_gear_request_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t torque_request;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->target_gear = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->drive_mode = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->accel_pedal = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    torque_request = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    torque_request |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->torque_request = (int16_t)torque_request;
    dst_p->vehicle_speed = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->vehicle_speed |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->brake_pressed = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->fault_clear = unpack_right_shift_u8(src_p[6], 1u, 0x02u);
    dst_p->force_shift = unpack_right_shift_u8(src_p[6], 2u, 0x04u);
    dst_p->vcu_ready = unpack_right_shift_u8(src_p[6], 3u, 0x08u);
    dst_p->counter520 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

int zf8hp_tcu_vcu_gear_request_init(struct zf8hp_tcu_vcu_gear_request_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_vcu_gear_request_t));

    return 0;
}

uint8_t zf8hp_tcu_vcu_gear_request_target_gear_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_target_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_target_gear_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_vcu_gear_request_target_gear_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_drive_mode_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_drive_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_drive_mode_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_vcu_gear_request_drive_mode_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_accel_pedal_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double zf8hp_tcu_vcu_gear_request_accel_pedal_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool zf8hp_tcu_vcu_gear_request_accel_pedal_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

bool zf8hp_tcu_vcu_gear_request_accel_pedal_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

int16_t zf8hp_tcu_vcu_gear_request_torque_request_encode(double value)
{
    return (int16_t)(value);
}

double zf8hp_tcu_vcu_gear_request_torque_request_decode(int16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_torque_request_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_vcu_gear_request_torque_request_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

uint16_t zf8hp_tcu_vcu_gear_request_vehicle_speed_encode(double value)
{
    return (uint16_t)(value / 0.01);
}

double zf8hp_tcu_vcu_gear_request_vehicle_speed_decode(uint16_t value)
{
    return ((double)value * 0.01);
}

bool zf8hp_tcu_vcu_gear_request_vehicle_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_vcu_gear_request_vehicle_speed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 655.35));
}

uint8_t zf8hp_tcu_vcu_gear_request_brake_pressed_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_brake_pressed_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_brake_pressed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_gear_request_brake_pressed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_fault_clear_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_fault_clear_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_fault_clear_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_gear_request_fault_clear_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_force_shift_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_force_shift_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_force_shift_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_gear_request_force_shift_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_vcu_ready_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_vcu_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_vcu_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_gear_request_vcu_ready_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_gear_request_counter520_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_gear_request_counter520_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_gear_request_counter520_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_vcu_gear_request_counter520_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

int zf8hp_tcu_vcu_vehicle_info_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_vcu_vehicle_info_t *src_p,
    size_t size)
{
    uint16_t actual_torque;
    uint16_t motor_rpm;
    uint8_t motor_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    actual_torque = (uint16_t)src_p->actual_torque;
    dst_p[0] |= pack_left_shift_u16(actual_torque, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(actual_torque, 8u, 0xffu);
    motor_rpm = (uint16_t)src_p->motor_rpm;
    dst_p[2] |= pack_left_shift_u16(motor_rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(motor_rpm, 8u, 0xffu);
    motor_temp = (uint8_t)src_p->motor_temp;
    dst_p[4] |= pack_left_shift_u8(motor_temp, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->battery_soc, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->charging_active, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->regen_allowed, 1u, 0x02u);
    dst_p[6] |= pack_left_shift_u8(src_p->hv_present, 2u, 0x04u);
    dst_p[6] |= pack_left_shift_u8(src_p->torque_cut_ack, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->counter521, 0u, 0x0fu);

    return (8);
}

int zf8hp_tcu_vcu_vehicle_info_unpack(
    struct zf8hp_tcu_vcu_vehicle_info_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t actual_torque;
    uint16_t motor_rpm;
    uint8_t motor_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    actual_torque = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    actual_torque |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->actual_torque = (int16_t)actual_torque;
    motor_rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    motor_rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->motor_rpm = (int16_t)motor_rpm;
    motor_temp = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->motor_temp = (int8_t)motor_temp;
    dst_p->battery_soc = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->charging_active = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->regen_allowed = unpack_right_shift_u8(src_p[6], 1u, 0x02u);
    dst_p->hv_present = unpack_right_shift_u8(src_p[6], 2u, 0x04u);
    dst_p->torque_cut_ack = unpack_right_shift_u8(src_p[6], 3u, 0x08u);
    dst_p->counter521 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

int zf8hp_tcu_vcu_vehicle_info_init(struct zf8hp_tcu_vcu_vehicle_info_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_vcu_vehicle_info_t));

    return 0;
}

int16_t zf8hp_tcu_vcu_vehicle_info_actual_torque_encode(double value)
{
    return (int16_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_actual_torque_decode(int16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_actual_torque_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_vcu_vehicle_info_actual_torque_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int16_t zf8hp_tcu_vcu_vehicle_info_motor_rpm_encode(double value)
{
    return (int16_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_motor_rpm_decode(int16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_motor_rpm_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_vcu_vehicle_info_motor_rpm_is_in_phys_range(double value)
{
    return ((value >= -32768.0) && (value <= 32767.0));
}

int8_t zf8hp_tcu_vcu_vehicle_info_motor_temp_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double zf8hp_tcu_vcu_vehicle_info_motor_temp_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool zf8hp_tcu_vcu_vehicle_info_motor_temp_is_in_range(int8_t value)
{
    return (value >= 0);
}

bool zf8hp_tcu_vcu_vehicle_info_motor_temp_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_battery_soc_encode(double value)
{
    return (uint8_t)(value / 0.5);
}

double zf8hp_tcu_vcu_vehicle_info_battery_soc_decode(uint8_t value)
{
    return ((double)value * 0.5);
}

bool zf8hp_tcu_vcu_vehicle_info_battery_soc_is_in_range(uint8_t value)
{
    return (value <= 200u);
}

bool zf8hp_tcu_vcu_vehicle_info_battery_soc_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_charging_active_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_charging_active_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_charging_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_vehicle_info_charging_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_regen_allowed_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_regen_allowed_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_regen_allowed_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_vehicle_info_regen_allowed_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_hv_present_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_hv_present_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_hv_present_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_vehicle_info_hv_present_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_torque_cut_ack_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_torque_cut_ack_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_torque_cut_ack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_vcu_vehicle_info_torque_cut_ack_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_vcu_vehicle_info_counter521_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_vcu_vehicle_info_counter521_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_vcu_vehicle_info_counter521_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_vcu_vehicle_info_counter521_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

int zf8hp_tcu_tcu_status1_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_status1_t *src_p,
    size_t size)
{
    uint8_t oil_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->current_gear, 0u, 0x0fu);
    dst_p[0] |= pack_left_shift_u8(src_p->target_gear_echo, 4u, 0xf0u);
    dst_p[1] |= pack_left_shift_u8(src_p->tcu_state, 0u, 0x0fu);
    dst_p[1] |= pack_left_shift_u8(src_p->shift_in_progress, 4u, 0x10u);
    dst_p[1] |= pack_left_shift_u8(src_p->tcu_ready, 5u, 0x20u);
    dst_p[1] |= pack_left_shift_u8(src_p->any_fault, 6u, 0x40u);
    dst_p[1] |= pack_left_shift_u8(src_p->park_lock, 7u, 0x80u);
    dst_p[2] |= pack_left_shift_u16(src_p->input_shaft_rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->input_shaft_rpm, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->output_shaft_rpm, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->output_shaft_rpm, 8u, 0xffu);
    oil_temp = (uint8_t)src_p->oil_temp;
    dst_p[6] |= pack_left_shift_u8(oil_temp, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->line_pressure, 0u, 0xffu);

    return (8);
}

int zf8hp_tcu_tcu_status1_unpack(
    struct zf8hp_tcu_tcu_status1_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t oil_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->current_gear = unpack_right_shift_u8(src_p[0], 0u, 0x0fu);
    dst_p->target_gear_echo = unpack_right_shift_u8(src_p[0], 4u, 0xf0u);
    dst_p->tcu_state = unpack_right_shift_u8(src_p[1], 0u, 0x0fu);
    dst_p->shift_in_progress = unpack_right_shift_u8(src_p[1], 4u, 0x10u);
    dst_p->tcu_ready = unpack_right_shift_u8(src_p[1], 5u, 0x20u);
    dst_p->any_fault = unpack_right_shift_u8(src_p[1], 6u, 0x40u);
    dst_p->park_lock = unpack_right_shift_u8(src_p[1], 7u, 0x80u);
    dst_p->input_shaft_rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->input_shaft_rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->output_shaft_rpm = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->output_shaft_rpm |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    oil_temp = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->oil_temp = (int8_t)oil_temp;
    dst_p->line_pressure = unpack_right_shift_u8(src_p[7], 0u, 0xffu);

    return (0);
}

int zf8hp_tcu_tcu_status1_init(struct zf8hp_tcu_tcu_status1_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_tcu_status1_t));

    return 0;
}

uint8_t zf8hp_tcu_tcu_status1_current_gear_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_current_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_current_gear_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_tcu_status1_current_gear_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t zf8hp_tcu_tcu_status1_target_gear_echo_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_target_gear_echo_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_target_gear_echo_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_tcu_status1_target_gear_echo_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t zf8hp_tcu_tcu_status1_tcu_state_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_tcu_state_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_tcu_state_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_tcu_status1_tcu_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}

uint8_t zf8hp_tcu_tcu_status1_shift_in_progress_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_shift_in_progress_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_shift_in_progress_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_status1_shift_in_progress_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_status1_tcu_ready_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_tcu_ready_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_tcu_ready_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_status1_tcu_ready_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_status1_any_fault_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_any_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_any_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_status1_any_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_status1_park_lock_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status1_park_lock_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_park_lock_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_status1_park_lock_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t zf8hp_tcu_tcu_status1_input_shaft_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_status1_input_shaft_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_input_shaft_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status1_input_shaft_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t zf8hp_tcu_tcu_status1_output_shaft_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_status1_output_shaft_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status1_output_shaft_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status1_output_shaft_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

int8_t zf8hp_tcu_tcu_status1_oil_temp_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double zf8hp_tcu_tcu_status1_oil_temp_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool zf8hp_tcu_tcu_status1_oil_temp_is_in_range(int8_t value)
{
    return (value >= 0);
}

bool zf8hp_tcu_tcu_status1_oil_temp_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}

uint8_t zf8hp_tcu_tcu_status1_line_pressure_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double zf8hp_tcu_tcu_status1_line_pressure_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool zf8hp_tcu_tcu_status1_line_pressure_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status1_line_pressure_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 25.5));
}

int zf8hp_tcu_tcu_status2_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_status2_t *src_p,
    size_t size)
{
    uint8_t tcu_hw_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->sol_a_current, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->sol_a_current, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->sol_b_current, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->sol_b_current, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->fault_bits, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fault_bits, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->shift_count, 0u, 0xffu);
    tcu_hw_temp = (uint8_t)src_p->tcu_hw_temp;
    dst_p[7] |= pack_left_shift_u8(tcu_hw_temp, 0u, 0xffu);

    return (8);
}

int zf8hp_tcu_tcu_status2_unpack(
    struct zf8hp_tcu_tcu_status2_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint8_t tcu_hw_temp;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->sol_a_current = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->sol_a_current |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->sol_b_current = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->sol_b_current |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->fault_bits = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fault_bits |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->shift_count = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    tcu_hw_temp = unpack_right_shift_u8(src_p[7], 0u, 0xffu);
    dst_p->tcu_hw_temp = (int8_t)tcu_hw_temp;

    return (0);
}

int zf8hp_tcu_tcu_status2_init(struct zf8hp_tcu_tcu_status2_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_tcu_status2_t));

    return 0;
}

uint16_t zf8hp_tcu_tcu_status2_sol_a_current_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_status2_sol_a_current_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status2_sol_a_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status2_sol_a_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t zf8hp_tcu_tcu_status2_sol_b_current_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_status2_sol_b_current_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status2_sol_b_current_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status2_sol_b_current_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint16_t zf8hp_tcu_tcu_status2_fault_bits_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_status2_fault_bits_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status2_fault_bits_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status2_fault_bits_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t zf8hp_tcu_tcu_status2_shift_count_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_status2_shift_count_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_status2_shift_count_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_status2_shift_count_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

int8_t zf8hp_tcu_tcu_status2_tcu_hw_temp_encode(double value)
{
    return (int8_t)(value - -40.0);
}

double zf8hp_tcu_tcu_status2_tcu_hw_temp_decode(int8_t value)
{
    return ((double)value + -40.0);
}

bool zf8hp_tcu_tcu_status2_tcu_hw_temp_is_in_range(int8_t value)
{
    return (value >= 0);
}

bool zf8hp_tcu_tcu_status2_tcu_hw_temp_is_in_phys_range(double value)
{
    return ((value >= -40.0) && (value <= 215.0));
}

int zf8hp_tcu_tcu_shift_status_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_shift_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->shift_phase, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->torque_cut_request, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->shift_active, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->shift_fault_code, 5u, 0xe0u);
    dst_p[1] |= pack_left_shift_u8(src_p->shift_ramp_percent, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->shift_elapsed_ms, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->shift_elapsed_ms, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->current_clutch_set, 0u, 0x1fu);
    dst_p[5] |= pack_left_shift_u8(src_p->target_clutch_set, 0u, 0x1fu);
    dst_p[6] |= pack_left_shift_u8(src_p->ramping_in_clutch_set, 0u, 0x1fu);
    dst_p[7] |= pack_left_shift_u8(src_p->ramping_out_clutch_set, 0u, 0x1fu);

    return (8);
}

int zf8hp_tcu_tcu_shift_status_unpack(
    struct zf8hp_tcu_tcu_shift_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->shift_phase = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->torque_cut_request = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->shift_active = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->shift_fault_code = unpack_right_shift_u8(src_p[0], 5u, 0xe0u);
    dst_p->shift_ramp_percent = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->shift_elapsed_ms = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->shift_elapsed_ms |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->current_clutch_set = unpack_right_shift_u8(src_p[4], 0u, 0x1fu);
    dst_p->target_clutch_set = unpack_right_shift_u8(src_p[5], 0u, 0x1fu);
    dst_p->ramping_in_clutch_set = unpack_right_shift_u8(src_p[6], 0u, 0x1fu);
    dst_p->ramping_out_clutch_set = unpack_right_shift_u8(src_p[7], 0u, 0x1fu);

    return (0);
}

int zf8hp_tcu_tcu_shift_status_init(struct zf8hp_tcu_tcu_shift_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_tcu_shift_status_t));

    return 0;
}

uint8_t zf8hp_tcu_tcu_shift_status_shift_phase_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_shift_phase_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_shift_phase_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool zf8hp_tcu_tcu_shift_status_shift_phase_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_torque_cut_request_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_torque_cut_request_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_torque_cut_request_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_shift_status_torque_cut_request_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_shift_active_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_shift_active_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_shift_active_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_shift_status_shift_active_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_shift_fault_code_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_shift_fault_code_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_shift_fault_code_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool zf8hp_tcu_tcu_shift_status_shift_fault_code_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_shift_ramp_percent_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_shift_ramp_percent_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_shift_ramp_percent_is_in_range(uint8_t value)
{
    return (value <= 100u);
}

bool zf8hp_tcu_tcu_shift_status_shift_ramp_percent_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 100.0));
}

uint16_t zf8hp_tcu_tcu_shift_status_shift_elapsed_ms_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_shift_status_shift_elapsed_ms_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_shift_elapsed_ms_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_shift_status_shift_elapsed_ms_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_current_clutch_set_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_current_clutch_set_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_current_clutch_set_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool zf8hp_tcu_tcu_shift_status_current_clutch_set_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 31.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_target_clutch_set_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_target_clutch_set_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_target_clutch_set_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool zf8hp_tcu_tcu_shift_status_target_clutch_set_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 31.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_ramping_in_clutch_set_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_ramping_in_clutch_set_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_ramping_in_clutch_set_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool zf8hp_tcu_tcu_shift_status_ramping_in_clutch_set_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 31.0));
}

uint8_t zf8hp_tcu_tcu_shift_status_ramping_out_clutch_set_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_shift_status_ramping_out_clutch_set_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_shift_status_ramping_out_clutch_set_is_in_range(uint8_t value)
{
    return (value <= 31u);
}

bool zf8hp_tcu_tcu_shift_status_ramping_out_clutch_set_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 31.0));
}

int zf8hp_tcu_tcu_pump_status_pack(
    uint8_t *dst_p,
    const struct zf8hp_tcu_tcu_pump_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->pump_state, 0u, 0x07u);
    dst_p[0] |= pack_left_shift_u8(src_p->pump_run_ack, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->pump_lin_fault, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->pump_alt_fault, 5u, 0x20u);
    dst_p[2] |= pack_left_shift_u16(src_p->pump_rpm, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->pump_rpm, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->pump_voltage, 0u, 0xffu);
    dst_p[5] |= pack_left_shift_u8(src_p->pump_current_raw, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->pump_retry_count, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->counter542, 0u, 0x0fu);

    return (8);
}

int zf8hp_tcu_tcu_pump_status_unpack(
    struct zf8hp_tcu_tcu_pump_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->pump_state = unpack_right_shift_u8(src_p[0], 0u, 0x07u);
    dst_p->pump_run_ack = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->pump_lin_fault = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->pump_alt_fault = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->pump_rpm = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->pump_rpm |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->pump_voltage = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->pump_current_raw = unpack_right_shift_u8(src_p[5], 0u, 0xffu);
    dst_p->pump_retry_count = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->counter542 = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);

    return (0);
}

int zf8hp_tcu_tcu_pump_status_init(struct zf8hp_tcu_tcu_pump_status_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct zf8hp_tcu_tcu_pump_status_t));

    return 0;
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_state_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_state_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_state_is_in_range(uint8_t value)
{
    return (value <= 7u);
}

bool zf8hp_tcu_tcu_pump_status_pump_state_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 7.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_run_ack_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_run_ack_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_run_ack_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_pump_status_pump_run_ack_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_lin_fault_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_lin_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_lin_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_pump_status_pump_lin_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_alt_fault_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_alt_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_alt_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

bool zf8hp_tcu_tcu_pump_status_pump_alt_fault_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 1.0));
}

uint16_t zf8hp_tcu_tcu_pump_status_pump_rpm_encode(double value)
{
    return (uint16_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_rpm_decode(uint16_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_rpm_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_pump_status_pump_rpm_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 65535.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_voltage_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double zf8hp_tcu_tcu_pump_status_pump_voltage_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool zf8hp_tcu_tcu_pump_status_pump_voltage_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_pump_status_pump_voltage_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 25.5));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_current_raw_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_current_raw_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_current_raw_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_pump_status_pump_current_raw_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_pump_retry_count_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_pump_retry_count_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_pump_retry_count_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

bool zf8hp_tcu_tcu_pump_status_pump_retry_count_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 255.0));
}

uint8_t zf8hp_tcu_tcu_pump_status_counter542_encode(double value)
{
    return (uint8_t)(value);
}

double zf8hp_tcu_tcu_pump_status_counter542_decode(uint8_t value)
{
    return ((double)value);
}

bool zf8hp_tcu_tcu_pump_status_counter542_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

bool zf8hp_tcu_tcu_pump_status_counter542_is_in_phys_range(double value)
{
    return ((value >= 0.0) && (value <= 15.0));
}
